---
title: "4. Association with epidemiological factors"
author: "Chiara Herzog"
date: "May 31, 2022"
output:
  rmarkdown::html_document:
    theme: cosmo
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)

library(dplyr)
library(tidyverse)
library(ggplot2)
library(ggsci)
library(patchwork)
library(gt)
library(pROC)
library(bdpv)
library(epiR)

# Set colours and themes
font <- theme_set(
  theme(text = element_text(family = "Guardian Sans")
  )
)
cols <- pal_jama(alpha = 0.8)(7)

# Read in data
load("../0-data/WID-qEC_manuscript_data.Rdata")
load("../0-data/cutoff.Rdata")

# Scripts
source("../1-source-codes/compute_ci_diff.R")
```


## FORECEE Validation (Figure S11)

```{r, fig.align="center", fig.width = 9, fig.height = 3.5}
tmp <- mldat %>%
  filter(set == "FORECEE Validation") %>%
  mutate(grade = as.character(grade),
         stage = as.character(stage),
         hist = as.character(hist)) %>%
  mutate(grade = ifelse(type == "Control", "Control", grade)) %>%
  mutate(stage = ifelse(type == "Control", "Control", stage)) %>%
  mutate(hist = ifelse(type == "Control", "Control",
                       ifelse(hist == "Other *", "Other", hist))) %>%
  mutate(grade = factor(grade, levels = c("Control", "Grade I", "Grade II", "Grade III", "Unknown"))) %>%
  mutate(hist = factor(hist, levels = c("Control", "Endometrioid", "Serous", "Clear cell", "Other", "Unknown"))) %>%
  mutate(stage = factor(stage, levels = c("Control", "I", "II", "III/IV", "Unknown"))) %>%
  mutate(sum = sum + 0.00001)

p1 <- tmp %>%
  ggplot(aes(x = age,
             y = log(sum),
             colour = type)) +
  geom_point(size = 0.3) +
  geom_smooth(method = "lm",
              se = FALSE) +
  geom_hline(yintercept = log(0.03),
             linetype = "dotted",
             colour = cols[1]) +
  annotate("text",
           x = 40,
           y = log(0.03)-1,
           label = "Threshold",
           size = 3,
           colour = cols[1]) +
  ylab(expression(paste(atop(bold("WID™-qEC"), "log (Σ PMR)")))) +
  theme(panel.background = element_blank(),
        legend.position = c(0.32, 1.1),
        legend.key = element_blank()) +
  scale_colour_manual(values = cols[c(1,2)],
                      name = "") +
  xlab("Age") +
  coord_cartesian(ylim = c(-11, 5.5),
                  clip = "off")


tmp <- tmp %>%
  pivot_longer(c(stage, grade, hist), names_to = "types", values_to = "factors")  %>%
  mutate(factors = factor(factors, levels = c("Control",
                                              "I", "II", "III/IV",
                                              "Grade I", "Grade II", "Grade III",
                                              "Endometrioid", "Serous", "Clear cell", "Other",
                                              "Unknown")))

labs <- c("Stage", "Grade", "Histology")
names(labs) <- c("stage", "grade", "hist")

p2 <- tmp %>%
  mutate(types = factor(types, levels = c("stage", "grade", "hist"))) %>%
  ggplot(aes(x = factors,
             y = log(sum))) +
  geom_violin(width = 0.4,
              aes(colour = type)) +
  geom_jitter(size = 0.3,
              aes(colour = type)) +
  ylab(expression(paste(atop(bold("WID™-qEC"), "log (Σ PMR)")))) +
  xlab("") +
  scale_colour_manual(values = cols[c(1,2)],
                      name = "") +
  geom_hline(yintercept = log(0.03),
             linetype = "dotted",
             colour = cols[1]) +
  facet_wrap(~types,
             scales = "free_x",
             labeller = labeller(types = labs)) +
  theme(panel.grid = element_blank(),
        legend.position = "none",
        axis.text.x = element_text(angle = 60,
                                   hjust = 1,
                                   margin = margin(-12, 0, 0, 0)),
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.background = element_blank(),
        plot.margin = margin(10, 10, 20, 10))

plot <- (p1 + p2) +
  plot_layout(widths = c(1.2, 2.5)) + 
  plot_annotation(tag_levels = "A") & 
  theme(axis.title.x = element_text(margin = margin(t=-20)))

plot
```

## Barcelona Validation (Figure S12)

```{r, fig.align="center", fig.width = 9, fig.height = 3.5}
tmp <- mldat %>%
  filter(set == "Barcelona Validation") %>%
  mutate(grade = as.character(grade),
         stage = as.character(stage),
         hist = as.character(hist)) %>%
  mutate(grade = ifelse(type == "Control", "Control", grade)) %>%
  mutate(stage = ifelse(type == "Control", "Control", stage)) %>%
  mutate(hist = ifelse(type == "Control", "Control",
                       ifelse(hist == "Other *", "Other",
                              hist))) %>%
  mutate(grade = factor(grade, levels = c("Control", "Grade I", "Grade II", "Grade III", "Unknown"))) %>%
  mutate(hist = factor(hist, levels = c("Control", "Endometrioid", "Serous", "Clear cell", "Other", "Unknown"))) %>%
  mutate(stage = factor(stage, levels = c("Control", "I", "II", "III/IV", "Unknown"))) %>%
  mutate(sum = sum + 0.00001)


p1 <- tmp %>%
  filter(!is.na(type)) %>%
  ggplot(aes(x = age,
             y = log(sum),
             colour = type)) +
  geom_point(size = 0.3) +
  geom_smooth(method = "lm",
              se = FALSE) +
  geom_hline(yintercept = log(0.03),
             linetype = "dotted",
             colour = cols[1]) +
  annotate("text",
           x = 40,
           y = log(0.03)-1,
           label = "Threshold",
           size = 3,
           colour = cols[1]) +
  theme(panel.grid = element_blank(),
        legend.position = c(0.32, 1.1),
        axis.title.x = element_text(margin = margin(t = -20, r = 0, b = 0, l = 0)),
        legend.key = element_blank(),
        panel.background = element_blank()) +
  scale_colour_manual(values = cols[c(1,2)],
                      name = "") +
  xlab("Age") +
  ylab(expression(paste(atop(bold("WID™-qEC"), "log ("~Sigma~" PMR)"))))


tmp <- tmp %>%
  pivot_longer(c(stage, grade, hist), names_to = "types", values_to = "factors")  %>%
  mutate(factors = factor(factors, levels = c("Control",
                                              "I", "II", "III/IV",
                                              "Grade I", "Grade II", "Grade III",
                                              "Endometrioid", "Serous", "Clear cell", "Other",
                                              "Unknown")))%>%
  mutate(sum = sum + 0.00001)

labs <- c("Stage", "Grade", "Histology")
names(labs) <- c("stage", "grade", "hist")

p2 <- tmp %>%
  mutate(types = factor(types, levels = c("stage", "grade", "hist"))) %>%
  ggplot(aes(x = factors,
             y = log(sum))) +
  geom_violin(width = 0.4,
              aes(colour = type)) +
  geom_jitter(size = 0.3,
              aes(colour = type)) +
  scale_colour_manual(values = cols[c(1,2)],
                      name = "") +
  geom_smooth() + 
  geom_hline(yintercept = log(0.03),
             linetype = "dotted",
             colour = cols[1]) +
  ylab(expression(paste(atop(bold("WID™-qEC"), "log ("~Sigma~" PMR)")))) + 
  xlab("") +
  facet_wrap(~types,
             scales = "free_x",
             labeller = labeller(types = labs)) +
  theme(panel.grid = element_blank(),
        legend.position = "none",
        axis.text.x = element_text(angle = 60,
                                   hjust = 1,
                                   margin = margin(-12, 0, 0, 0)),
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        plot.margin = margin(10, 10, 20, 10))

plot <- (p1 + p2) +
  plot_layout(widths = c(1.2, 2.5)) + 
  plot_annotation(tag_levels = "A") & 
  theme(axis.title.x = element_text(margin = margin(t=-20)))

plot
```

## Ethnicity (Table S3)

```{r}
mldat_tmp <- mldat %>%
  filter(set == "FORECEE Validation" & !is.na(ethnicity) & ethnicity != "Unknown")%>%
  mutate(ethnicity = factor(ethnicity, levels = c("White", "Non-white"))) %>%
  droplevels() %>%
  mutate(thresh1 = case_when(sum >= cut$threshold[1] ~ "Endometrial cancer",
                             sum < cut$threshold[1] ~ "Control")) %>%
  mutate(type = factor(type, levels = c("Endometrial cancer", "Control"))) %>%
  mutate(thresh1 = factor(thresh1, levels = c("Endometrial cancer", "Control")))  %>%
  mutate(disease = case_when(type=="Endometrial cancer" ~ 1,
                           type == "Control" ~ 0),
       score = case_when(thresh1 == "Endometrial cancer" ~ 1,
                         thresh1 == "Control" ~ 0))

# create df
dat <- data.frame(matrix(nrow = 6, ncol = length(unique(mldat_tmp$ethnicity))+1))
colnames(dat) <- c(levels(mldat_tmp$ethnicity), "type")
dat$type <- c("Endometrial cancers  – n", "Cancer-free controls  – n", c("Sensitivity – % (95% CI)", "Specificity – % (95% CI)", "PPV – % (95% CI) †", "NPV – % (95% CI) †"))

for(i in  1:length(levels(mldat_tmp$ethnicity))){
  name <- levels(mldat_tmp$ethnicity)[i]
  set <- unique(mldat_tmp$set)
  tmp <- mldat_tmp %>%
    filter(ethnicity == name)
  pop_prev <- 0.09
  
  tab <- table(tmp$thresh1, tmp$type)
  # rval <- summary(epi.tests(tab))
  tab <- matrix(c(tab[1,1], tab[2,1], tab[1,2], tab[2,2]), ncol = 2)
  colnames(tab) <- c("Case", "Control")
  rownames(tab) <- c("Case", "Control")
  rval2 <- BDtest(xmat=as.matrix(tab), pr=pop_prev, conf.level = 0.95)
  
  dat[1,i] <- sum(tmp$type=="Endometrial cancer")
  dat[2,i] <- sum(tmp$type=="Control")
  dat[3,i] <- paste0(round(rval2$SESPDAT$Estimate[1],2)*100, " (",
                     round(rval2$SESPDAT$`Lower 97.5% limit`[1],2)*100, "–",
                     round(rval2$SESPDAT$`Upper 97.5% limit`[1],2)*100, ")")
  dat[4,i] <- paste0(round(rval2$SESPDAT$Estimate[2],2)*100, " (",
                     round(rval2$SESPDAT$`Lower 95% limit`[2],2)*100, "–",
                     round(rval2$SESPDAT$`Upper 97.5% limit`[2],2)*100, ")")
  dat[5,i] <- paste0(round(rval2$PPVNPVDAT$Estimate[2],2)*100, " (",
                     round(rval2$PPVNPVDAT$`Lower 97.5% limit`[2],2)*100, "–",
                     round(rval2$PPVNPVDAT$`Upper 97.5% limit`[2],2)*100, ")")
  dat[6,i] <- paste0(round(rval2$PPVNPVDAT$Estimate[1],2)*100, " (",
                     round(rval2$PPVNPVDAT$`Lower 95% limit`[1],2)*100, "–",
                     round(rval2$PPVNPVDAT$`Upper 97.5% limit`[1],2)*100, ")")
}

x <- compute_ci_diff(mldat_tmp$disease, mldat_tmp$score, mldat_tmp$ethnicity, t  = 1.96)

dat$`∆` <- ""
dat$`∆`[3] <- paste0(round(x$diff[1]*100, 1), " (",
                     round(x$cil[1]*100, 1), "–",
                     round(x$ciu[1]*100, 1), ")")
dat$`∆`[4] <- paste0(round(x$diff[2]*100, 1), " (",
                                  round(x$cil[2]*100, 1), "–",
                                  round(x$ciu[2]*100, 1), ")") 
dat$`∆`[5] <- paste0(round(x$diff[3]*100, 1), " (",
                     round(x$cil[3]*100, 1), "–",
                     round(x$ciu[3]*100, 1), ")")
dat$`∆`[6] <- paste0(round(x$diff[4]*100, 1), " (",
                     round(x$cil[4]*100, 1), "–",
                     round(x$ciu[4]*100, 1), ")") 


tbl <- dat %>%
  gt(rowname_col = "type") %>%
  cols_label(
    White = "White ethnicity",
    `Non-white` = "Non-white ethnicity",
    `∆` = html("<i>Difference *</i>")
  ) %>%
  tab_style(
    style = cell_text(color = "#707173"),
    locations = list(cells_body(
      columns = "∆",
      rows = everything()
    ),
    cells_column_labels(columns = "∆")
    )) %>%
  text_transform(locations = cells_body(),
                      fn = function(x){
                        paste0(ifelse(x == "NA", "",
                                      ifelse(x == "7.5 (2.5–12.5)",
                                             html("<b>7.5 (2.5–12.5)</b"),
                                             ifelse(x == "-1.8 (-1.9–-1.6)",
                                                    html("<b>-1.8 (-1.9–-1.6)</b>"), x))))}) %>%
  tab_style(
    style = list(
      cell_text(align = "left")
    ),
    locations = cells_stub(rows = TRUE)
  ) %>%
  tab_options(table.font.names = "Guardian Sans",
              column_labels.font.weight = "bold",
              row_group.font.weight = "bold",
              data_row.padding = 2,
              column_labels.font.size = 12,
              table.font.size = 10,
              row_group.padding = 2,
              row_group.border.right.width = px(10),
              summary_row.padding = 2,
              table.border.top.color = "white",
              row_group.border.top.width = px(1),
              table.width = px(600),
              row_group.border.bottom.width = px(1),
              stub.border.width = px(0),
              heading.title.font.size = 14) %>% 
  gt::tab_source_note(gt::html("* Difference in sensitivity, specificity, PPV, and NPV (including confidence interval) for white and non-white ethnicity.<br><b>PPV</b> denotes positive predictive value, <b>NPV</b> negative predictive value.<br>† Assumed population prevalence: 9%"))

tbl
```
