---
title: "6. Lynch Cohort"
author: "Chiara Herzog"
date: May 31, 2022
output:
  rmarkdown::html_document:
    theme: cosmo
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)

library(dplyr)
library(tidyverse)
library(ggplot2)
library(ggsci)
cols <- pal_jama(alpha = 0.8)(7)

font <- theme_set(
  theme(text = element_text(family = "Guardian Sans")
  )
)

# Read in data
load("../0-data/WID-qEC_manuscript_data.Rdata")
load("../0-data/cutoff.Rdata")
```


## Time to diagnosis (Figure S15)

```{r}
mldat %>%
  filter(set == "Lynch Cohort") %>%
  ggplot(aes(x = type,
             y = log(sum+0.0001))) +
  geom_violin(aes(colour = type),
              width = 0.2) +
  geom_jitter(size = 0.75,
              aes(colour = type)) +
  scale_colour_jama() +
  theme(panel.background = element_blank(),
        legend.key = element_blank(),
        legend.position = "top",
        legend.title = element_blank()) +
  xlab("") +
  ylab(expression(paste(atop(bold("WID™-qEC"), "log (Σ PMR)")))) +
  geom_hline(yintercept = log(0.03),
             linetype = "dotted",
             colour = cols[1]) +
  geom_hline(yintercept = log(0.63),
             linetype = "dotdash",
             colour = cols[1]) +
  annotate("text",
           x = 2.3,
           y = log(0.03)-0.3,
           label = "Threshold 1",
           size = 3,
           colour = cols[1])
```