---
title: "7. Karolinska Cohort"
author: "Chiara Herzog"
date: May 31, 2022
output:
  rmarkdown::html_document:
    theme: cosmo
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)

library(dplyr)
library(tidyverse)
library(ggplot2)
library(gt)
library(epiR)
library(bdpv)
font <- theme_set(
  theme(text = element_text(family = "Guardian Sans")
  )
)

# Read in data
load("../0-data/WID-qEC_manuscript_data.Rdata")
load("../0-data/cutoff.Rdata")

# Source scripts
source("../1-source-codes/compute_ci_diff.R")
```


## Sensitivity and specificity depending on time to diagnosis (Table S7)

```{r}
tmp <- mldat %>%
  filter(set == "Karolinska Cohort" & !is.na(time_to_diagnosis)) %>%
  mutate(y = case_when(time_to_diagnosis<365 ~ "<1y",
                       time_to_diagnosis>=365 ~ ">=1y")) %>%
  mutate(y = factor(y, levels = c("<1y", ">=1y"))) %>%
  mutate(sum_cutoff = case_when(sum >= cut$threshold[2] ~ "positive",
                                 sum < cut$threshold[2] ~ "negative")) %>%
  mutate(type = factor(type, levels = c("Endometrial cancer", "Control")),
         sum_cutoff = factor(sum_cutoff, levels = c("positive", "negative"))) %>%
  mutate(disease = case_when(type=="Endometrial cancer" ~ 1,
                           type == "Control" ~ 0),
       score = case_when(sum_cutoff == "positive" ~ 1,
                         sum_cutoff == "negative" ~ 0)) %>%
  droplevels()

dat <- data.frame(matrix(nrow = 5, ncol = 3))
colnames(dat) <- c("type", "<1y", "≥1y")
dat$type <- c("Endometrial cancers – n",
                    "Cancer-free controls – n",
                    "Time to event, median (IQR)", 
                    "Sensitivity – % (95% CI)",
                    "Specificity – % (95% CI)")

for (i in 1:length(levels(tmp$y))){
  time <- levels(tmp$y)[i]
  pop_prev = 0.0009
  
  tmp2 <- tmp %>%
    filter(y == time) %>%
    droplevels()
  
  tab <- table(tmp2$sum_cutoff, tmp2$type)
  # rval <- summary(epi.tests(tab))
  tab <- matrix(c(tab[1,1], tab[2,1], tab[1,2], tab[2,2]), ncol = 2)
  colnames(tab) <- c("Case", "Control")
  rownames(tab) <- c("Case", "Control")
  rval2 <- BDtest(xmat=as.matrix(tab), pr=pop_prev, conf.level = 0.95)
  
  x <- summary(tmp2$time_to_diagnosis)
  
  dat[1,i+1] <- nrow(tmp2[tmp2$type=="Endometrial cancer",])
  dat[2,i+1] <- nrow(tmp2[tmp2$type=="Control",])
  dat[3,i+1] <- paste0(round(median(tmp2$time_to_diagnosis),0), " (", 
                       round(x[2],0), "-",
                       round(x[5],0), ")")
  dat[4,i+1] <- paste0(round(rval2$SESPDAT$Estimate[1]*100,1), " (",
                       round(rval2$SESPDAT$`Lower 97.5% limit`[1]*100, 1), "-",
                       round(rval2$SESPDAT$`Upper 97.5% limit`[1]*100,1), ")")
  dat[5,i+1] <- paste0(round(rval2$SESPDAT$Estimate[2]*100,1), " (",
                       round(rval2$SESPDAT$`Lower 95% limit`[2]*100, 1), "-",
                       round(rval2$SESPDAT$`Upper 97.5% limit`[2]*100,1), ")")
  
}

tmp <- tmp %>%
  mutate(y = factor(y, levels = c(">=1y", "<1y")))

x <- compute_ci_diff(tmp$disease, tmp$score, tmp$y, t  = 1.989)
dat$d <- ''
dat$d[4] <- paste0(round(x$diff[1]*100, 1), " (",
                                             ifelse(round(x$cil[1]*100, 1)<(-100), "-100", round(x$cil[1]*100, 1)), "–",
                                             round(x$ciu[1]*100, 1), ")")
dat$d[5] <- paste0(round(x$diff[2]*100, 1), " (",
                                             round(x$cil[2]*100, 1), "–",
                                             round(x$ciu[2]*100, 1), ")") 

tbl <- dat %>%
  gt(rowname_col = "type", groupname_col = "threshold") %>%
  cols_label("<1y" = "<1 y to follow-up",
             "≥1y" = "≥1 y to follow-up",
             "d" = html("<i>Difference *</i>")) %>%
  tab_style(
    style = list(
      cell_text(align = "left")
    ),
    locations = cells_stub(rows = TRUE)
  ) %>%
  text_transform(locations = cells_body(),
                 fn = function(x){
                   paste0(ifelse(x == "-70.9 (-100–-38)", html("<b>-70.9 (-100–-38)</b"), x))}) %>%
  tab_style(
    style = cell_text(color = "#707173"),
    locations = list(cells_body(
      columns = "d",
      rows = everything()
    ),
    cells_column_labels(columns = "d")
    )) %>%
  tab_options(table.font.names = "Guardian Sans",
              column_labels.font.weight = "bold",
              row_group.font.weight = "bold",
              data_row.padding = 2,
              column_labels.font.size = 12,
              table.font.size = 10,
              row_group.padding = 2,
              table.width = px(500),
              row_group.border.right.width = px(10),
              summary_row.padding = 2,
              table.border.top.color = "white",
              row_group.border.top.width = px(1),
              row_group.border.bottom.width = px(1),
              stub.border.width = px(0),
              heading.title.font.size = 14)
tbl
```
